### ISSUE TITLE
Feel like updating it for Python 3?

### ISSUE THREAD

**Issue by garyjblackwell** [secretsquirrel/recomposer#2]
Just guessing at the issue without doing any troubleshooting myself.
python.exe recomposer.py -f tsserv.exe -a
  File "recomposer.py", line 220
    print "Old file name:", FILE
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Old file name:", FILE)?

**Comment by secretsquirrel** [comment]
I accept pull requests.
